dist: trusty
sudo: require

language: c
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6

script:

    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - export CC=/usr/bin/gcc-6
    - gcc -v

    - gcc -std=c99 mglsl.h
